dows:
  sdk:
    builders:
      weixin-open:
        dialect: java
        build-tool: maven
        groupId: org.dows.sdk
        artifactId: weixin-sdk
        version: 1.0.0-SNAPSHOT
        base-package: org.dows.sdk.weixin.open
        builders:
          - org.dows.sdk.builder.EntityBuilder
          - org.dows.sdk.builder.RestBuilder
          - org.dows.sdk.builder.YmlBuilder
        childs:
          - artifactId: weixin-api

      weixin-pay:
        dialect: java
        build-tool: maven
        groupId: org.dows.sdk
        artifactId: weixin-sdk
        version: 1.0.0-SNAPSHOT
        base-package: org.dows.sdk.weixin.pay
