dows:
  sdk:
    modules:
      weixin-open:
        groupId: org.dows.sdk
        artifactId: weixin-sdk
        version: 1.0.0-SNAPSHOT
        base-package: org.dows.sdk.weixin.open
        childs:
          - artifactId: weixin-api

      weixin-pay:
        dialect: java
        build-tool: maven
        groupId: org.dows.sdk
        artifactId: weixin-sdk
        version: 1.0.0-SNAPSHOT
        base-package: org.dows.sdk.weixin.pay
