dows:
  sdk:
    builders:
      weixin-open:
        dialect: java
        build-tool: maven
        groupId: org.dows.sdk
        artifactId: weixin-sdk
        version: 1.0.0-SNAPSHOT
        pkg: org.dows.sdk.weixin.open
        path: e:/workspaces/projects/java/demo
        dependencies:
          - org.dows.sdk:weixin-sdk:1.0.0-SNAPSHOT
        builders:
          - org.dows.sdk.builder.EntityBuilder
          - org.dows.sdk.builder.RestBuilder
#        childs:
#          - artifactId: weixin-api

      weixin-pay:
        dialect: java
        build-tool: maven
        groupId: org.dows.sdk
        artifactId: weixin-sdk
        version: 1.0.0-SNAPSHOT
        base-package: org.dows.sdk.weixin.pay
