dows:
  sdk:
    templates:
      weixin-open:
        dialect: java
        builder: maven
        groupId: org.dows.sdk
        artifactId: weixin-sdk
        version: 1.0.0-SNAPSHOT
        base-package: org.dows.sdk.weixin.open
        childs:
          - artifactId: weixin-sdk

